# Path definitions

set IABOTWATCH = "/home/greenc/toolforge/iabotwatch/"

set AWK = "/usr/local/bin/awk"
set SED = "/bin/sed"
set PS = "/bin/ps"
set GREP = "/bin/grep"
set SLEEP = "/bin/sleep"
set ECHO = "/bin/echo"
set DATE = "/bin/date"
set CURL = "/usr/bin/curl"
set LS = "/bin/ls"
set RM = "/bin/rm"
set BC = "/usr/bin/bc"
set HEAD = "/usr/bin/head"
set SORT = "/usr/bin/sort"
set UNIQ = "/usr/bin/uniq"
set CP = "/bin/cp"
set MV = "/bin/mv"
set CAT = "/bin/cat"
set TOUCH = "/usr/bin/touch"
